#CustomChat v1.6 Config
#CompliantVersion 1.7.2〜1.9.4
#ColorCodeList http://ess.khhq.net/mc/

#バージョンチェック、ダウンロード
#このプラグインが最新バージョンかチェックします。
#メッセージはOPにしか表示されません。
# trueで有効 falseで無効
UpdateChecker: true
AutoDownload: true

#チャットに使用するカラーコードの設定
# trueで有効 falseで無効
ChatColorCode:
  Enable: true
  ColorCode: '&'

#NGワードの設定
#NGワードはngword_s-jis.yml、ngword_utf-8.ymlで設定できます。
#&で色を指定できます。ColorCodeListのURL参照
#MessageTypeの設定
#broadcastでサーバー全体にメッセージを送信します。
#sendでNGワードに引っかかったプレイヤーにメッセージを送信します。
#NGMessageの設定
#%prefixでPermissionsExのPrefixを取得します。
#%suffixでPermissionsExのSuffixを取得します。
#%playerでプレイヤーを取得します。
#%worldでワールドを取得します。
#%messageでプレイヤーのチャットを取得します。
# trueで有効 falseで無効
NGword:
  Enable: true
  MessageType: send
  NGMessage: '&cNGワードが含まれています'

#チャットグループの設定 
#ChatGroups:
#  (グループ名): <チャットメッセージ>
#&で色を指定できます。ColorCodeListのURL参照
#%prefixでPermissionsExのPrefixを取得します。
#%suffixでPermissionsExのSuffixを取得します。
#%timeで現在の時刻を取得します。
#%playerでプレイヤーを取得します。
#%worldでワールドを取得します。
#%messageでプレイヤーのチャットを取得します。
#%japanizeでローマ字を日本語化します。
#設定は追加できます
ChatGroups:
  Admin: '&4[Admin]&b%player: &f%message &7(%japanize)'
  Default: '<%player> %message'

#通常プレイヤーの設定
#NormalPlayers: <グループ名>
NormalPlayers: Default

#指定したプレイヤーの設定
#Players:
#  (プレイヤーID):
#    Group: <グループ名> 
Players:
  testplayer:
    Group: Admin