#CustomChat Config
#BukkitVersion 1.7.2～1.9
#ColorCodeList http://ess.khhq.net/mc/

#バージョンチェック、ダウンロード
#このプラグインが最新バージョンかチェックします。
#メッセージはOPにしか表示されません。
# trueで有効 falseで無効
UpdateChecker: true
AutoDownload: true

#NGワードの設定
#NGワードはngword_s-jis.yml、ngword_utf-8.ymlで設定できます。
#&で色を指定できます。ColorCodeListのURL参照
#MessageTypeの設定
#broadcastでサーバー全体にメッセージを送信します。
#sendでNGワードに引っかかったプレイヤーにメッセージを送信します。
#NGMessageの設定
#%playerでプレイヤーを取得します。
#%messageでプレイヤーのチャットを取得します。
# trueで有効 falseで無効
NGword:
  Enable: true
  MessageType: send
  NGMessage: '&cNGワードが含まれています'

#チャットの設定
#ChatGroupsの設定方法 
#ChatGroups:
#  (グループ名): <チャットメッセージ>
#&で色を指定できます。ColorCodeListのURL参照
#%playerでプレイヤーを取得します。
#%chatでプレイヤーのチャットを取得します。
#%jp ローマ字の日本語化
#設定は追加できます
ChatGroups:
  Admin: '&4[Admin]&b%player: &f%chat &7(%jp)'
  Default: '<%player> %chat'

#NormalPlayersの設定
#NormalPlayers設定方法
#NormalPlayers: <グループ名>
NormalPlayers: Default

#Players設定方法
#Players:
#  (プレイヤーID):
#    Group: <グループ名> 
Players:
  testplayer:
    Group: Admin