name: CustomChat
main: com.github.yuttyann.customchat.Main
version: 1.5
softdepend: [Vault, PermissionsEx]
author: yuttyann44581
website: http://ch.nicovideo.jp/yuttyann44581/blomaga/ar810622

commands:
  customchat:
    description: Config再読み込みコマンド
    usage: /<command> reload - Configの再読み込みをします。